### PR TITLE
adding a fix to support variables as params

### LINKED ISSUE #84: [Bug]: @inlinedImage only works with static urls
### What happened?

The new Blade directive `@inlinedImage` only works when passing static strings as image URLs or paths. When dynamically passing value from a Variable it does not work, as it does not resolve the value correctly.

**This does work:**
```blade
<div>
   @inlinedImage('https://picsum.photos/200/300')
</div>
```

**This does NOT work:**
```blade
<div>
   @php $src = 'https://picsum.photos/200/300' @endphp
   @inlinedImage($src)
</div>
```

This is an example of an Error I've got:

```
file_get_contents(public/$src): Failed to open stream: No such file or directory
```

Should a Blade directive not just return valid PHP source code to be evaluated by the view engine to work properly?

IMHO this should be more like this:

```php
Blade::directive('inlinedImage', function ($expression) {
            return "<?php
                \$url = \Illuminate\Support\Str::of(with({$expression}))->trim(\"'\")->trim('\"')->__toString();
        
                if (! \Illuminate\Support\Str::of(\$url)->startsWith(['http://', 'https://'])) {
                    \$path = public_path(\$url);
                    if (file_exists(\$path)) {
                        \$imageContent = 'data:image/png;base64,' . base64_encode(file_get_contents(\$path));
                        echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                    }
                } else {
                    try {
                        \$response = \Illuminate\Support\Facades\Http::get(\$url);
                        if (\$response->successful()) {
                            \$imageContent = 'data:image/png;base64,' . base64_encode(\$response->body());
                            echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                        }
                    } catch (\Exception \$e) {
                        throw new \RuntimeException('Failed to fetch the image: ' . \$e->getMessage());
                    }
                }
            ?>";
        });
```

If someone can confirm this error does occur too, I will create a PR for fixing this.

### How to reproduce the bug

Use the `inlinedImage` Blade directive provided by this package.

```blade
<div>
   @php $src = 'https://picsum.photos/200/300' @endphp
   @inlinedImage($src)
</div>
```

### Package Version

1.2.0

### PHP Version

8.2.0

### Laravel Version

10.43.0

### Which operating systems does with happen with?

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by ArielMejiaDev**
# What makes this PR

close #84 

This does work:

```php
<div>
   @inlinedImage('https://picsum.photos/200/300')
</div>
```

This does NOT work:

```php
<div>
   @php $src = 'https://picsum.photos/200/300' @endphp
   @inlinedImage($src)
</div>
```

As far as I understand any service provider is executed too early in an application lifecycle, so it cannot evaluate a variable value that is set in a controller.

To solve this all the code is now executed at the same time to be executed in the blade file directly.

The solution is probably not so elegant, but solves both cases, static strings and variables as params

## Explanation with the solution

https://www.loom.com/share/00cc167045d04310ae194ac2af157d07?sid=a984958f-c830-4077-b263-684eda2378d6

@freekmurze if you can imagine a better solution I would be glad to implement it, thanks

### CODE REVIEW

**Comment by ArielMejiaDev** [comment]
> There's now quite some duplication in the try/catch block which makes it hard to see what exactly is being catched.
> 
> Refactor this so that a variable `$content` is being set in the try/catch block. Under the try/catch block return the full image HTML. This will make it more readable.

Hi @freekmurze I found a complicate scenario that is why the code is written in this way, with the current code in `main` branch:

```php
@inlinedImage('assets/images/logo.png')
```

Works as this code inside the package service provider is getting:

```php
Blade::directive('inlinedImage', function ($url) {
    dd($url); // returns the string "assets/images/logo.png"            
});
```

But with a variable from a controller or using php directive to set it:

```php
@php $image = 'assets/images/logo.png'; @endphp

@inlinedImage($image)
```

It returns the variable name as a string

```php
Blade::directive('inlinedImage', function ($url) {
    dd($url); // returns the string "$image"            
});
```

I think this is a limitation I think because it is too early in the application lifecycle, so a variable is replaced I think when Blade compiles, that is why I had to set all the code at once.

If I set a `$content` variable if a `file_content` at that moment in the runtime (with a variable param) the code would execute something like this:

```php
$content = base64_encode(file_get_contents(asset("$url")));
// or
$content = base64_encode(Http::get("$url"));


I think I did not miss anything, I would be looking forward your feedback, and thanks!

```

**Comment by ArielMejiaDev** [comment]
# The Last commits make `@inlinedImage`:

[x] Works with static string as params
[x] Works with variables as params
[x] Cleanup Blade Directive Code
[x] Always returns an exception if an image fails to fetch (absolute path) or is not found (relative path)

## Demo

https://www.loom.com/share/a7a760129c93452cb1006ff4cf21de53?sid=73be0c89-de9b-4367-aa6a-8b4c5118bdc1

It should close #84

**Review by freekmurze — COMMENTED** [review]
Could you add tests for this to ensure that it works correctly?

**Comment by ArielMejiaDev** [comment]
Hi @freekmurze I know that you are probably a lot more busy, if you have any chance to check these new changes that add tests to generate images for headers and footers please let me know.

I am glad to help and if there is any feedback it would be welcome, I let you know how ingenious looks the `workbench` implementation is to test generated files from the package.

**Comment by freekmurze** [comment]
Thanks! I'll check on `main` if the tests pass there.

**Comment by freekmurze** [comment]
The tests are failing, could you send another PR to fix them?

**Pull request merged**
